---
title: "Lista 03"
author: "Matheus Soares - RA:277210"
format: typst
editor: visual
---

### Conexão com SQLite

```{r}
library(DBI)
library(RSQLite)
con <- dbConnect(SQLite(), "me315.sqlite")
```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 1. Exiba os valores de `STATE` e `FEE` da tabela `PRESERVE` mas sem duplicados.

```{sql connection = con}
SELECT DISTINCT STATE, FEE FROM PRESERVE
```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 2. Exiba todos os valores de `DNO` na tabela `EMPLOYEE`. Não exiba valores duplicados.

```{sql connection = con}

SELECT DISTINCT DNO FROM EMPLOYEE

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 3. Execute as `QUERYS` a seguir. Examine as tabelas resultantes e faça as observações relevantes.

#### - SELECT `DNO`, `SALARY` FROM `EMPLOYEE`

#### - SELECT DISTINCT `DNO`, `SALARY` FROM `EMPLOYEE`

#### - SELECT DISTINCT `DNO`, `SALARY` FROM `EMPLOYEE` ORDER BY `DNO`, `SALARY`

```{sql connection = con}

SELECT DNO, SALARY FROM EMPLOYEE

```

```{sql connection = con}

SELECT DISTINCT DNO, SALARY FROM EMPLOYEE

```

```{sql connection = con}

SELECT DISTINCT DNO, SALARY FROM EMPLOYEE ORDER BY DNO, SALARY

```

A distinção é visivel, a partir, da segunda e terceira QUERY pelo fato que a "função" `DISTINCT` não tem valor lógico, uma vez que não há valores iguais para o mesmo `SALARY`.

Assim observamos uma ordenação com o `ORDER BY` que organiza o os valores distintos em ordem crescente baseados nas colunas `DNO`, e em seguida, `SALARY`.

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 4. Exiba todas as informações sobre qualquer reserva natural em Montana que seja menor que 1.000 acres.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE STATE = "MT" AND ACRES <= 1000

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 5. Exiba todas as informações sobre qualquer reserva natural cujo valor de ACRES esteja entre 1200 e 15000, inclusive.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE STATE = "MT" AND ACRES >= 1200 AND ACRES <= 15000

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 6. Exiba todas as informações sobre qualquer reserva natural localizada em Montana que não possua taxa de entrada e seja maior que 10.000 acres.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE STATE = "MT" AND FEE = 0 AND ACRES >= 10000

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 7. Exiba todas as informações sobre as reservas naturais localizadas em Montana ou Massachusetts.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE STATE = "MT" OR STATE = "MA"

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 8. Exiba todas as informações sobre qualquer reserva natural localizada em Montana ou qualquer reserva que seja menor que 1.000 acres.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE STATE = "MT" OR ACRES < 1000

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 9. Exiba o número e o nome de qualquer reserva natural que possua taxa de entrada que não seja igual a zero.

```{sql connection = con}

SELECT PNO, PNAME FROM PRESERVE
WHERE FEE != 0

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 10. Exiba o número e o nome das reservas naturais que não possuem taxa de entrada de US$ 3,00 e não possuem taxa de US$ 10,00.

```{sql connection = con}

SELECT PNO, PNAME FROM PRESERVE
WHERE FEE != 3 AND FEE != 10
```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 11. Exiba todas as informações sobre qualquer reserva natural localizada no Arizona que não possua taxa de entrada, ou qualquer reserva que seja menor que 100 acres (independentemente de seus valores de `STATE` e `FEE`).

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE (STATE = "AZ" AND FEE = 0) OR ACRES < 100

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 12. Exiba todas as informações sobre qualquer reserva natural que seja menor que 1.000 acres e tenha taxa de entrada de zero dólares ou esteja localizada no Arizona.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE (ACRES < 1000 AND FEE = 0) OR STATE = "AZ"

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 13. Selecione todas as informações sobre qualquer reserva natural com taxa de entrada que não seja maior que zero, ou qualquer outra reserva, independentemente de sua taxa, que esteja localizada em Montana e seja maior que 1.000 acres.

```{sql connection = con}

SELECT * FROM PRESERVE
WHERE FEE <= 0 OR (STATE = "MT" AND ACRES > 1000)

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 14. Exiba todas as informações sobre todas as reservas naturais, exceto aquelas reservas de Montana sem taxa de entrada.

```{sql connection = con}

SELECT * FROM PRESERVE 
WHERE NOT (STATE = "MT" AND FEE = 0)

```

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 15. As seguintes cláusulas WHERE são logicamente equivalentes?

WHERE STATE = 'MA' AND (ACRES > 1000 OR FEE = 0.0)
WHERE (STATE = 'MA' AND ACRES > 1000) OR (STATE = 'MA' AND FEE = 0.0)

R: SIM, as clausulas são equivalentes por comutatividade, seguindo o exemplo, C1 AND (C2 OR C3) = (C1 AND C2) OR (C1 AND C3).

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 16. As seguintes cláusulas WHERE são logicamente equivalentes?

WHERE STATE = 'MA' OR (ACRES > 1000 AND FEE = 0.0)
WHERE (STATE = 'MA' OR ACRES > 1000) AND (STATE = 'MA' OR FEE = 0.0)

R: SIM, são equivalentes por comutatividade, seguindo o exemplo, C1 OR (C2 AND C3) = (C1 OR C2) AND (C1 OR C3).

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 17. As seguintes cláusulas WHERE são logicamente equivalentes?

WHERE NOT (ACRES < 50 AND STATE = 'MA')
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
WHERE ACRES >= 50 OR STATE <> 'MA'

R: SIM, todas seguem a lógica de `ACRES` maior que 50, e que `STATE` seja diferente de "MA" (Massachusetts).

## \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### 18. As seguintes cláusulas WHERE são logicamente equivalentes?

WHERE NOT (ACRES < 50 OR STATE = 'MA')
WHERE NOT ACRES < 50 OR NOT STATE = 'MA'
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'

R: NÃO, a segunda cláusula vai realizar uma busca aonde `ACRES` serão menores que 50 **OU** `STATE` seja diferente de "MA" (Massachusetts), isso está errado pois a condição exige uma busca com os dois fatores determinantes não apenas um.
