---
title: "Lab_06"
author: "Matheus Soares - RA:277210"
format:
  html:
    embed-resources: true
editor: visual
---

### Pacotes

```{r}
library(DBI)
library(RSQLite)
library(dplyr)
```

### 1. Caminho do arquivo

```{r}
path <- "dados"
fname <- file.path(path, "disco.db")
```

### 2. Conectando ao banco

```{r}
conn <- dbConnect(RSQLite::SQLite(), fname)
```

### 3. Tabelas existentes

```{r}
dbListTables(conn)
```

### 4. Colunas da tabela customers

```{r}
dbListFields(conn, "customers")
```

### 5. Número de clientes

```{r}
dbGetQuery(conn, "SELECT COUNT(*) AS total_clientes FROM customers")
```

### 6. Número de países diferentes

```{r}
dbGetQuery(conn, "SELECT COUNT(DISTINCT Country) AS total_paises FROM customers")
```

### 7. Clientes por país

```{r}
dbGetQuery(conn, "
  SELECT Country, COUNT(*) AS total
  FROM customers
  GROUP BY Country
  ORDER BY total DESC
")
```

### 8. Top 5 países com mais clientes

```{r}
dbGetQuery(conn, "
  SELECT Country, COUNT(*) AS total
  FROM customers
  GROUP BY Country
  ORDER BY total DESC
  LIMIT 5
")
```

### 9. Países com nome de 6 letras

```{r}
dbGetQuery(conn, "
  SELECT DISTINCT Country
  FROM customers
  WHERE Country GLOB '??????'
")
```

### 10. Músicas compradas por clientes brasileiros

```{r}
dbGetQuery(conn, "
  SELECT DISTINCT t.Name
  FROM customers AS c
  INNER JOIN invoices AS i ON c.CustomerId = i.CustomerId
  INNER JOIN invoice_items AS ii ON i.InvoiceId = ii.InvoiceId
  INNER JOIN tracks AS t ON ii.TrackId = t.TrackId
  WHERE c.Country = 'Brazil'
")
```

### 11. Desconectando

```{r}
dbDisconnect(conn)
```
